/**
 * Epic Chunked-Build rolling hash (HashPoly64) — the `RollingHash` field on
 * every chunk in `FChunkDataList`. 64-bit polynomial hash with polynomial
 * `0xC96C5795D7870F42`, generated byte-by-byte via a 256-entry lookup table.
 *
 * Used by `chunk-decoder.ts` to verify the decompressed chunk payload
 * matches the rolling hash declared in the manifest.
 */

const POLY: bigint = 0xc96c5795d7870f42n
const MASK_64: bigint = 0xffffffffffffffffn

/** Rotate-left a 64-bit unsigned bigint by `n` bits. */
function rotl64(v: bigint, n: bigint): bigint {
  return ((v << n) & MASK_64) | (v >> (64n - n))
}

/**
 * 256-entry lookup table built with Epic BuildPatchTool's algorithm. For each
 * starting byte `b`, iterate 8 times: shift right by 1, and if the LSB
 * BEFORE shifting was set, XOR the shifted value with `POLY`. The result is
 * `table[b]`.
 *
 * Computed once at module load; the loop in `poly64Hash` is then a single
 * XOR + rotate-left per input byte.
 */
const HASH_TABLE: BigUint64Array = (() => {
  const tab = new BigUint64Array(256)
  for (let b = 0; b < 256; b++) {
    let v = BigInt(b)
    for (let i = 0; i < 8; i++) {
      if ((v & 1n) === 1n) {
        v >>= 1n
        v ^= POLY
      } else {
        v >>= 1n
      }
    }
    tab[b] = v
  }
  return tab
})()

/**
 * Compute the 64-bit rolling hash of `buf`. Empty buffer → 0n.
 * Caller is expected to format the result as 16-char hex uppercase to
 * compare against the manifest field.
 */
export function poly64Hash(buf: Buffer): bigint {
  let state = 0n
  for (let i = 0; i < buf.length; i++) {
    state = rotl64(state, 1n) ^ HASH_TABLE[buf[i]]
  }
  return state
}
